apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-29T09:48:16Z"
  labels:
    app: weather-app
  name: weather-app
  namespace: default
  resourceVersion: "4341"
  uid: 53fe79bf-ee6e-401c-b1e3-a2e1540871cc
spec:
  clusterIP: 10.96.176.125
  clusterIPs:
  - 10.96.176.125
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32738
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: weather-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
